spring:
  application:
    name: order-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://ep-rough-tooth-a1n1hdki-pooler.ap-southeast-1.aws.neon.tech/major-project?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_4Kk0IiANmMtQ
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000