# Application
spring.application.name="Product Service"
server.port=8083

# MongoDB
spring.mongodb.uri=${MONGODB_URI}

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Eureka 
eureka.client.enabled=false

# Logging 
logging.level.org.springframework=INFO
logging.level.com.virtualstore=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG