spring:
  application:
    name: productservice

  mongodb:
    uri: mongodb+srv://admin:pass1234@ecommerce-cluster-0.el6cazo.mongodb.net/store
eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework: INFO
    com.virutualstore: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

